// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM002_Logout_Cancel</b><br>
 * Generated     : <b>2012/11/11 4:26:45 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 11, 2012
 * @author David
 */
public abstract class PSM002_Logout_CancelHelper extends RationalTestScript
{
	/**
	 * Logout: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"), anchor, flags);
	}
	
	/**
	 * SystemMessage: with default state.
	 *		.captionText : System Message
	 * 		.class : Interface.Messages
	 * 		accessibleContext.accessibleName : System Message
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject systemMessage() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("systemMessage"));
	}
	/**
	 * SystemMessage: with specific test context and state.
	 *		.captionText : System Message
	 * 		.class : Interface.Messages
	 * 		accessibleContext.accessibleName : System Message
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject systemMessage(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("systemMessage"), anchor, flags);
	}
	
	/**
	 * YouHaveSucessfullyLoggedOut: with default state.
	 *		text : You have sucessfully logged out.
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : You have sucessfully logged out.
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject youHaveSucessfullyLoggedOut() 
	{
		return new GuiTestObject(
                        getMappedTestObject("youHaveSucessfullyLoggedOut"));
	}
	/**
	 * YouHaveSucessfullyLoggedOut: with specific test context and state.
	 *		text : You have sucessfully logged out.
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : You have sucessfully logged out.
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject youHaveSucessfullyLoggedOut(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("youHaveSucessfullyLoggedOut"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point YouHaveSucessfullyLoggedOut_standard object in the SUT.
	 */
	protected IFtVerificationPoint YouHaveSucessfullyLoggedOut_standardVP() 
	{
		return vp("YouHaveSucessfullyLoggedOut_standard");
	}
	protected IFtVerificationPoint YouHaveSucessfullyLoggedOut_standardVP(TestObject anchor)
	{
		return vp("YouHaveSucessfullyLoggedOut_standard", anchor);
	}
	
	

	protected PSM002_Logout_CancelHelper()
	{
		setScriptName("PSM002_Logout_Cancel");
	}
	
}

