// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM001_Login_15MinWarning</b><br>
 * Generated     : <b>2012/11/12 8:48:20 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 12, 2012
 * @author David
 */
public abstract class PSM001_Login_15MinWarningHelper extends RationalTestScript
{
	/**
	 * _15MinutesLeft: with default state.
	 *		text : 15 Minutes Left
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : 15 Minutes Left
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _15MinutesLeft() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_15MinutesLeft"));
	}
	/**
	 * _15MinutesLeft: with specific test context and state.
	 *		text : 15 Minutes Left
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : 15 Minutes Left
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _15MinutesLeft(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_15MinutesLeft"), anchor, flags);
	}
	
	/**
	 * _5MinutesLeft: with default state.
	 *		text : 5 Minutes Left
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : 5 Minutes Left
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _5MinutesLeft() 
	{
		return new GuiTestObject(
                        getMappedTestObject("_5MinutesLeft"));
	}
	/**
	 * _5MinutesLeft: with specific test context and state.
	 *		text : 5 Minutes Left
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : 5 Minutes Left
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject _5MinutesLeft(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("_5MinutesLeft"), anchor, flags);
	}
	
	/**
	 * Deliverable2GoogleDriveGoogleChrome: with default state.
	 *		.text : Deliverable 2 - Google Drive - Google Chrome
	 * 		.class : Chrome_WidgetWin_1
	 * 		.processName : chrome.exe
	 * 		.name : Deliverable 2 - Google Drive - Google Chrome
	 */
	protected TopLevelSubitemTestObject deliverable2GoogleDriveGoogleC() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("deliverable2GoogleDriveGoogleC"));
	}
	/**
	 * Deliverable2GoogleDriveGoogleChrome: with specific test context and state.
	 *		.text : Deliverable 2 - Google Drive - Google Chrome
	 * 		.class : Chrome_WidgetWin_1
	 * 		.processName : chrome.exe
	 * 		.name : Deliverable 2 - Google Drive - Google Chrome
	 */
	protected TopLevelSubitemTestObject deliverable2GoogleDriveGoogleC(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("deliverable2GoogleDriveGoogleC"), anchor, flags);
	}
	
	/**
	 * EndOfClassReached: with default state.
	 *		text : End of Class Reached
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : End of Class Reached
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject endOfClassReached() 
	{
		return new GuiTestObject(
                        getMappedTestObject("endOfClassReached"));
	}
	/**
	 * EndOfClassReached: with specific test context and state.
	 *		text : End of Class Reached
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : End of Class Reached
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject endOfClassReached(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("endOfClassReached"), anchor, flags);
	}
	
	/**
	 * Login: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Login
	 * 		.classIndex : 0
	 */
	protected GuiTestObject login() 
	{
		return new GuiTestObject(
                        getMappedTestObject("login"));
	}
	/**
	 * Login: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Login
	 * 		.classIndex : 0
	 */
	protected GuiTestObject login(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("login"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : 15 Minutes Left
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : 15 Minutes Left
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : 5 Minutes Left
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : 5 Minutes Left
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok2(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok2"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : End of Class Reached
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok3() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok3"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : End of Class Reached
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok3(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok3"), anchor, flags);
	}
	
	/**
	 * PSMLogin: with default state.
	 *		.captionText : PSM Login
	 * 		.class : Interface.LoginForm
	 * 		accessibleContext.accessibleName : PSM Login
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmLogin() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmLogin"));
	}
	/**
	 * PSMLogin: with specific test context and state.
	 *		.captionText : PSM Login
	 * 		.class : Interface.LoginForm
	 * 		accessibleContext.accessibleName : PSM Login
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmLogin(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmLogin"), anchor, flags);
	}
	
	/**
	 * PSMMainMenu: with default state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"));
	}
	/**
	 * PSMMainMenu: with specific test context and state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"), anchor, flags);
	}
	
	/**
	 * SystemMessage: with default state.
	 *		.captionText : System Message
	 * 		.class : Interface.Messages
	 * 		accessibleContext.accessibleName : System Message
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject systemMessage() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("systemMessage"));
	}
	/**
	 * SystemMessage: with specific test context and state.
	 *		.captionText : System Message
	 * 		.class : Interface.Messages
	 * 		accessibleContext.accessibleName : System Message
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject systemMessage(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("systemMessage"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point EndOfClassReached_standard object in the SUT.
	 */
	protected IFtVerificationPoint EndOfClassReached_standardVP() 
	{
		return vp("EndOfClassReached_standard");
	}
	protected IFtVerificationPoint EndOfClassReached_standardVP(TestObject anchor)
	{
		return vp("EndOfClassReached_standard", anchor);
	}
	
	/**
	 * Locate and return the verification point EndOfClassReached_text object in the SUT.
	 */
	protected IFtVerificationPoint EndOfClassReached_textVP() 
	{
		return vp("EndOfClassReached_text");
	}
	protected IFtVerificationPoint EndOfClassReached_textVP(TestObject anchor)
	{
		return vp("EndOfClassReached_text", anchor);
	}
	
	/**
	 * Locate and return the verification point SystemMessage_state object in the SUT.
	 */
	protected IFtVerificationPoint SystemMessage_stateVP() 
	{
		return vp("SystemMessage_state");
	}
	protected IFtVerificationPoint SystemMessage_stateVP(TestObject anchor)
	{
		return vp("SystemMessage_state", anchor);
	}
	
	/**
	 * Locate and return the verification point SystemMessage_state_2 object in the SUT.
	 */
	protected IFtVerificationPoint SystemMessage_state_2VP() 
	{
		return vp("SystemMessage_state_2");
	}
	protected IFtVerificationPoint SystemMessage_state_2VP(TestObject anchor)
	{
		return vp("SystemMessage_state_2", anchor);
	}
	
	/**
	 * Locate and return the verification point _15MinutesLeft_standard object in the SUT.
	 */
	protected IFtVerificationPoint _15MinutesLeft_standardVP() 
	{
		return vp("_15MinutesLeft_standard");
	}
	protected IFtVerificationPoint _15MinutesLeft_standardVP(TestObject anchor)
	{
		return vp("_15MinutesLeft_standard", anchor);
	}
	
	/**
	 * Locate and return the verification point _5MinutesLeft_standard object in the SUT.
	 */
	protected IFtVerificationPoint _5MinutesLeft_standardVP() 
	{
		return vp("_5MinutesLeft_standard");
	}
	protected IFtVerificationPoint _5MinutesLeft_standardVP(TestObject anchor)
	{
		return vp("_5MinutesLeft_standard", anchor);
	}
	
	

	protected PSM001_Login_15MinWarningHelper()
	{
		setScriptName("PSM001_Login_15MinWarning");
	}
	
}

