// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM001_Login_ClearDB</b><br>
 * Generated     : <b>2012/11/12 12:18:32 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 12, 2012
 * @author David
 */
public abstract class PSM001_Login_ClearDBHelper extends RationalTestScript
{
	/**
	 * Cancel: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"), anchor, flags);
	}
	
	/**
	 * EditSchedule: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule() 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"));
	}
	/**
	 * EditSchedule: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 1
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 1
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"), anchor, flags);
	}
	
	/**
	 * Logout: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"), anchor, flags);
	}
	
	/**
	 * PleaseChoose: with default state.
	 *		.captionText : Please Choose
	 * 		.class : Interface.courseSelect
	 * 		accessibleContext.accessibleName : Please Choose
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject pleaseChoose() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("pleaseChoose"));
	}
	/**
	 * PleaseChoose: with specific test context and state.
	 *		.captionText : Please Choose
	 * 		.class : Interface.courseSelect
	 * 		accessibleContext.accessibleName : Please Choose
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject pleaseChoose(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("pleaseChoose"), anchor, flags);
	}
	
	/**
	 * PSMMainMenu: with default state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"));
	}
	/**
	 * PSMMainMenu: with specific test context and state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"), anchor, flags);
	}
	
	

	protected PSM001_Login_ClearDBHelper()
	{
		setScriptName("PSM001_Login_ClearDB");
	}
	
}

