// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM002_Logout_AfterEdit</b><br>
 * Generated     : <b>2012/11/12 4:10:34 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 12, 2012
 * @author David
 */
public abstract class PSM002_Logout_AfterEditHelper extends RationalTestScript
{
	/**
	 * CourseName: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Course Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiSubitemTestObject courseName() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("courseName"));
	}
	/**
	 * CourseName: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Course Name:
	 * 		.classIndex : 4
	 */
	protected TextGuiSubitemTestObject courseName(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("courseName"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject edit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("edit"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject edit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("edit"), anchor, flags);
	}
	
	/**
	 * EditSchedule: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule() 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"));
	}
	/**
	 * EditSchedule: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"), anchor, flags);
	}
	
	/**
	 * EditSchedule: with default state.
	 *		.captionText : Edit Schedule
	 * 		.class : Interface.PrefilledScheduleForm
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject editSchedule2() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("editSchedule2"));
	}
	/**
	 * EditSchedule: with specific test context and state.
	 *		.captionText : Edit Schedule
	 * 		.class : Interface.PrefilledScheduleForm
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject editSchedule2(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("editSchedule2"), anchor, flags);
	}
	
	/**
	 * EndDate: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : End Date:
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject endDate() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("endDate"));
	}
	/**
	 * EndDate: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : End Date:
	 * 		.classIndex : 1
	 */
	protected TextGuiSubitemTestObject endDate(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("endDate"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 1
	 * 		.itemText : {1234}
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 1
	 * 		.itemText : {1234}
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"), anchor, flags);
	}
	
	/**
	 * Logout: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout() 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"));
	}
	/**
	 * Logout: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Logout
	 * 		.classIndex : 8
	 */
	protected GuiTestObject logout(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("logout"), anchor, flags);
	}
	
	/**
	 * OK: with default state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : You have sucessfully logged out.
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok() 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"));
	}
	/**
	 * OK: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		.priorLabel : You have sucessfully logged out.
	 * 		accessibleContext.accessibleName : OK
	 * 		.classIndex : 0
	 */
	protected GuiTestObject ok(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("ok"), anchor, flags);
	}
	
	/**
	 * Save: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject save() 
	{
		return new GuiTestObject(
                        getMappedTestObject("save"));
	}
	/**
	 * Save: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Save
	 * 		.classIndex : 0
	 */
	protected GuiTestObject save(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("save"), anchor, flags);
	}
	
	/**
	 * StartDate: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Start Date:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject startDate() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("startDate"));
	}
	/**
	 * StartDate: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Start Date:
	 * 		.classIndex : 0
	 */
	protected TextGuiSubitemTestObject startDate(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("startDate"), anchor, flags);
	}
	
	/**
	 * Subject: with default state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Subject:
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject subject() 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("subject"));
	}
	/**
	 * Subject: with specific test context and state.
	 *		.class : javax.swing.JTextField
	 * 		.priorLabel : Subject:
	 * 		.classIndex : 2
	 */
	protected TextGuiSubitemTestObject subject(TestObject anchor, long flags) 
	{
		return new TextGuiSubitemTestObject(
                        getMappedTestObject("subject"), anchor, flags);
	}
	
	/**
	 * YouHaveSucessfullyLoggedOut: with default state.
	 *		text : You have sucessfully logged out.
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : You have sucessfully logged out.
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject youHaveSucessfullyLoggedOut() 
	{
		return new GuiTestObject(
                        getMappedTestObject("youHaveSucessfullyLoggedOut"));
	}
	/**
	 * YouHaveSucessfullyLoggedOut: with specific test context and state.
	 *		text : You have sucessfully logged out.
	 * 		.class : javax.swing.JLabel
	 * 		accessibleContext.accessibleName : You have sucessfully logged out.
	 * 		name : Message
	 * 		.classIndex : 0
	 */
	protected GuiTestObject youHaveSucessfullyLoggedOut(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("youHaveSucessfullyLoggedOut"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point YouHaveSucessfullyLoggedOut_standard object in the SUT.
	 */
	protected IFtVerificationPoint YouHaveSucessfullyLoggedOut_standardVP() 
	{
		return vp("YouHaveSucessfullyLoggedOut_standard");
	}
	protected IFtVerificationPoint YouHaveSucessfullyLoggedOut_standardVP(TestObject anchor)
	{
		return vp("YouHaveSucessfullyLoggedOut_standard", anchor);
	}
	
	

	protected PSM002_Logout_AfterEditHelper()
	{
		setScriptName("PSM002_Logout_AfterEdit");
	}
	
}

