// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM014_Schedule_Cancel2</b><br>
 * Generated     : <b>2012/11/11 9:56:34 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 11, 2012
 * @author David
 */
public abstract class PSM014_Schedule_Cancel2Helper extends RationalTestScript
{
	/**
	 * Cancel: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"), anchor, flags);
	}
	
	/**
	 * Edit: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject edit() 
	{
		return new GuiTestObject(
                        getMappedTestObject("edit"));
	}
	/**
	 * Edit: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit
	 * 		.classIndex : 0
	 */
	protected GuiTestObject edit(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("edit"), anchor, flags);
	}
	
	/**
	 * EditSchedule: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule() 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"));
	}
	/**
	 * EditSchedule: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.classIndex : 7
	 */
	protected GuiTestObject editSchedule(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("editSchedule"), anchor, flags);
	}
	
	/**
	 * EditSchedule: with default state.
	 *		.captionText : Edit Schedule
	 * 		.class : Interface.PrefilledScheduleForm
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject editSchedule2() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("editSchedule2"));
	}
	/**
	 * EditSchedule: with specific test context and state.
	 *		.captionText : Edit Schedule
	 * 		.class : Interface.PrefilledScheduleForm
	 * 		accessibleContext.accessibleName : Edit Schedule
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject editSchedule2(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("editSchedule2"), anchor, flags);
	}
	
	/**
	 * JComboBox: with default state.
	 *		.itemCount : 2
	 * 		.itemText : {1234,2345}
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox() 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"));
	}
	/**
	 * JComboBox: with specific test context and state.
	 *		.itemCount : 2
	 * 		.itemText : {1234,2345}
	 * 		.class : javax.swing.JComboBox
	 * 		.classIndex : 0
	 */
	protected TextSelectGuiSubitemTestObject jComboBox(TestObject anchor, long flags) 
	{
		return new TextSelectGuiSubitemTestObject(
                        getMappedTestObject("jComboBox"), anchor, flags);
	}
	
	/**
	 * PleaseChoose: with default state.
	 *		.captionText : Please Choose
	 * 		.class : Interface.courseSelect
	 * 		accessibleContext.accessibleName : Please Choose
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject pleaseChoose() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("pleaseChoose"));
	}
	/**
	 * PleaseChoose: with specific test context and state.
	 *		.captionText : Please Choose
	 * 		.class : Interface.courseSelect
	 * 		accessibleContext.accessibleName : Please Choose
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject pleaseChoose(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("pleaseChoose"), anchor, flags);
	}
	
	/**
	 * PSMMainMenu: with default state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"));
	}
	/**
	 * PSMMainMenu: with specific test context and state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point EditSchedule_state object in the SUT.
	 */
	protected IFtVerificationPoint EditSchedule_stateVP() 
	{
		return vp("EditSchedule_state");
	}
	protected IFtVerificationPoint EditSchedule_stateVP(TestObject anchor)
	{
		return vp("EditSchedule_state", anchor);
	}
	
	/**
	 * Locate and return the verification point PleaseChoose_state object in the SUT.
	 */
	protected IFtVerificationPoint PleaseChoose_stateVP() 
	{
		return vp("PleaseChoose_state");
	}
	protected IFtVerificationPoint PleaseChoose_stateVP(TestObject anchor)
	{
		return vp("PleaseChoose_state", anchor);
	}
	
	/**
	 * Locate and return the verification point PSMMainMenu_state object in the SUT.
	 */
	protected IFtVerificationPoint PSMMainMenu_stateVP() 
	{
		return vp("PSMMainMenu_state");
	}
	protected IFtVerificationPoint PSMMainMenu_stateVP(TestObject anchor)
	{
		return vp("PSMMainMenu_state", anchor);
	}
	
	

	protected PSM014_Schedule_Cancel2Helper()
	{
		setScriptName("PSM014_Schedule_Cancel2");
	}
	
}

