// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM014_EditSchedule_Cancel2</b><br>
 * Generated     : <b>2012/11/13 9:33:06 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 13, 2012
 * @author David
 */
public abstract class PSM014_EditSchedule_Cancel2Helper extends RationalTestScript
{
	/**
	 * Deliverable2GoogleDriveGoogleChrome: with default state.
	 *		.text : Deliverable 2 - Google Drive - Google Chrome
	 * 		.class : Chrome_WidgetWin_1
	 * 		.processName : chrome.exe
	 * 		.name : Deliverable 2 - Google Drive - Google Chrome
	 */
	protected TopLevelSubitemTestObject deliverable2GoogleDriveGoogleC() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("deliverable2GoogleDriveGoogleC"));
	}
	/**
	 * Deliverable2GoogleDriveGoogleChrome: with specific test context and state.
	 *		.text : Deliverable 2 - Google Drive - Google Chrome
	 * 		.class : Chrome_WidgetWin_1
	 * 		.processName : chrome.exe
	 * 		.name : Deliverable 2 - Google Drive - Google Chrome
	 */
	protected TopLevelSubitemTestObject deliverable2GoogleDriveGoogleC(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("deliverable2GoogleDriveGoogleC"), anchor, flags);
	}
	
	

	protected PSM014_EditSchedule_Cancel2Helper()
	{
		setScriptName("PSM014_EditSchedule_Cancel2");
	}
	
}

