// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>PSM004_Schedule_Cancel2</b><br>
 * Generated     : <b>2012/11/13 5:36:10 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 build 7601 Service Pack 1 <br>
 * 
 * @since  November 13, 2012
 * @author David
 */
public abstract class PSM004_Schedule_Cancel2Helper extends RationalTestScript
{
	/**
	 * AddClassSchedule: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Add Class Schedule
	 * 		.classIndex : 5
	 */
	protected GuiTestObject addClassSchedule() 
	{
		return new GuiTestObject(
                        getMappedTestObject("addClassSchedule"));
	}
	/**
	 * AddClassSchedule: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Add Class Schedule
	 * 		.classIndex : 5
	 */
	protected GuiTestObject addClassSchedule(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("addClassSchedule"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel() 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		.class : javax.swing.JButton
	 * 		accessibleContext.accessibleName : Cancel
	 * 		.classIndex : 1
	 */
	protected GuiTestObject cancel(TestObject anchor, long flags) 
	{
		return new GuiTestObject(
                        getMappedTestObject("cancel"), anchor, flags);
	}
	
	/**
	 * PSMMainMenu: with default state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"));
	}
	/**
	 * PSMMainMenu: with specific test context and state.
	 *		.captionText : PSM Main Menu
	 * 		.class : Interface.MainMenu
	 * 		accessibleContext.accessibleName : PSM Main Menu
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject psmMainMenu(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("psmMainMenu"), anchor, flags);
	}
	
	/**
	 * ScheduleSetup: with default state.
	 *		.captionText : Schedule Setup
	 * 		.class : Interface.ScheduleForm
	 * 		accessibleContext.accessibleName : Schedule Setup
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject scheduleSetup() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("scheduleSetup"));
	}
	/**
	 * ScheduleSetup: with specific test context and state.
	 *		.captionText : Schedule Setup
	 * 		.class : Interface.ScheduleForm
	 * 		accessibleContext.accessibleName : Schedule Setup
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject scheduleSetup(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("scheduleSetup"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point PSMMainMenu_state object in the SUT.
	 */
	protected IFtVerificationPoint PSMMainMenu_stateVP() 
	{
		return vp("PSMMainMenu_state");
	}
	protected IFtVerificationPoint PSMMainMenu_stateVP(TestObject anchor)
	{
		return vp("PSMMainMenu_state", anchor);
	}
	
	/**
	 * Locate and return the verification point ScheduleSetup_state object in the SUT.
	 */
	protected IFtVerificationPoint ScheduleSetup_stateVP() 
	{
		return vp("ScheduleSetup_state");
	}
	protected IFtVerificationPoint ScheduleSetup_stateVP(TestObject anchor)
	{
		return vp("ScheduleSetup_state", anchor);
	}
	
	

	protected PSM004_Schedule_Cancel2Helper()
	{
		setScriptName("PSM004_Schedule_Cancel2");
	}
	
}

